version: '3'

services:
  githooks:
    build:
      context: .
      dockerfile: Dockerfile.githooks
    volumes:
      - ./.git:/tmp/.git
      - ./hooks:/tmp/hooks

  citextract:
    image: kmjjacobs/citextract
    build: .
    volumes:
      - .:/app
    stdin_open: true
    tty: true